### ISSUE TITLE
users[i].has_ssn is not populating, and I can't see why...

### ISSUE THREAD

**Issue by aidanielson** [IllinoisLegalAidOnline/docassemble-USCISApplications#148] opened 2024-02-27 04:53 UTC
![image](https://github.com/aidanielson/docassemble-USCISApplications/assets/122302921/50f88fca-0bfb-4e21-afa2-01d1baa3eaf4)
![image](https://github.com/aidanielson/docassemble-USCISApplications/assets/122302921/07c4b8c0-2361-4a65-937f-cf43aece7b08)
![image](https://github.com/aidanielson/docassemble-USCISApplications/assets/122302921/c2342e5a-da94-4b9f-9796-ad2fef9d877c)

**Comment by nonprofittechy** [comment] 2024-03-12 17:48
Duplicate of #159

**Closed as not planned by nonprofittechy** 2024-03-12 17:48 UTC
Labels: duplicate
